name: cloudflare-dynamic-public-ip
services:

  monitor:
    image: ghcr.io/apolloroboto/rust-cloudflare-dynamic-public-ip:latest
    command: monitor
    restart: unless-stopped
    environment:
      CLOUDFLARE_TOKEN: "${CLOUDFLARE_TOKEN}"
      CLOUDFLARE_ZONE_ID: |
        b9bf66d603b6864d47a45ed8ebf36c8f # domain one
        73863c174616a20b1d99216d9ef9466b # domain two
      MQTT_ENABLED: "true"
      MQTT_HOST: localhost
      MQTT_PORT: "1883"
